server:
  port: 8790

spring:
  application:
    name: gateway


zuul:
  routes:
    data:
      path: /data/**
      serviceId: data
    config:
      path: /config/**
      serviceId: config

ribbon:
  eureka:
    enabled: true

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 60000

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8760/eureka/